### ISSUE TITLE
Workspace

### ISSUE THREAD

**Issue by sourencho** [hwacha/entale#11]
* Add workspace. Make it a translucent grid spanning the screen whose units correspond to the size of one symbol. Radial menu is available when workspace is active, and when it selects a symbol, it's placed on the grid in the first available rectangle portion of the grid that can accommodate the size of the expression (this will work like a 2D malloc).
* Moving keyboard keys will change which expression is highlighted in an associated direction.
* Press a key to select a highlighted expression. Selecting an expression on the workspace, you can:
    -  Move it into an open argument slot within another expression on the workspace. This partially applies the second expression to the selected expression as an argument, removing both expressions from the workspace.
    - Press the equip button to equip the expression to be uttered to an NPC.
* Zoom the workspace in and out (this increases the size of each unit square in the grid, making expressions larger or smaller)
* Scroll in x or y direction in the workspace.

**Comment by wgmarcy** [comment]
Current issues:
1. expressions on workspace are blended as though they're behind the workspace. This isn't the case. Solution: custom shader to manually control when each is rendered. This also prevents workspace from rendering in front of anything.

2. Cursor movement needs to be revamped to allow for diagonal movement; some pieces get stuck without any way to get to them otherwise. Solution: make a zig-zag search instead of a line out in the array elements out from each direction.

**Comment by wgmarcy** [comment]
The problems listed above are solved. However, there are a set of new problems and bugs that'll be left for later. Arranged in order of importance.

1. There is no automatic resize for the workspace. If an expression can't be placed in the current workspace, it causes the expression to disappear and various bugs crop up. Need to implement resize, scroll and zoom.

2. The cursor controls allow for diagonal movement, but lead to counter-intuitive cursor moves. Need to reimplement the grid to be more intuitive.

3. There needs to be a visual indication that an expression is currently selected.

4. After an expression is combined, the position of the cursor represented internally should be updated along with the pointer position (only the pointer is updated now).
